### ISSUE TITLE
Use Crystal's standard abstraction

### ISSUE THREAD

**Issue by trans** [anykeyh/xxHash.cr#1]
Hi,

I am using this library, as I wish to stick to pure Crystal if possible and not depend on a C binding. I ran into a problem though. I want to add a file and some extra data to the digest but don't see how.

I would like to update the code to use the standard Crystal digest abstraction (https://crystal-lang.org/api/latest/Digest.html). I looked at the source but don't quite understand it enough to figure out how to push additional data into the calculation.

If you can provide me with the insight on how to go about it, I'd be happy to work on it and submit a pull request.

Thanks.

**Comment by anykeyh** [comment]
That's a good idea actually. 
The problem with the current setup is that the finalization is not a method and is directly written into the digest part.

I'm not sure when I would have time to deal with it, but the change should be trivial.

```crystal
      buffer = uninitialized UInt8[16]
      slice = buffer.to_slice

      update(io, slice)
```

This is the Digest#update method

```crystal
      if @len >= 16
        hash = rotl(@v0, 1)  &+
               rotl(@v1, 7)  &+
               rotl(@v2, 12) &+
               rotl(@v3, 18)
      else
        hash = @seed &+ P5
      end

      hash = hash &+ @len

      p = 0
      while p <= (@ptr - 4)
        mem = b2i32(p, slice)
        hash = hash &+ mem &* P3
        hash = rotl(hash, 17) &* P4
        p += 4
      end

      while p < @ptr
        hash = hash &+ slice[p].to_u32 &* P5
        hash = rotl(hash, 11) &* P1
        p += 1
      end

      hash ^= hash >> 15
      hash = hash &* P2
      hash ^= hash >> 13
      hash = hash &* P3
      hash ^= hash >> 16

      hash
```

This is the finalize method.

I might have a few hours to spare in a few days. I keep a note. Happy to help if you are willing to give a try :)

**Comment by trans** [comment]
Hi, I managed to work it out for XXH64. Wasn't quite as simple as it seemed at first, but I persevered. I'm sure the code can still be improved, but it passes the tests you had made. 

At some point it probably would be a good idea to add some additional tests to make sure it's all working with the `Digest` abstract API as it should.

I will do the XXH32 version next week and then push it up to you.

**Comment by trans** [comment]
Here's the pull request https://github.com/anykeyh/xxHash.cr/pull/2
